baseURL = "https://blog.creepnt.stream"
languageCode = "en-us"
title = "CreepNT's blog"
disableKinds = ["section", "categories", "tags"]
disqusShortname = ""
pygmentsCodeFences = false
pygmentsUseClasses = false
paginate = 9999
minify = true
disableHugoGeneratorInject = true
enableEmoji = true

[taxonomies]
  tag = "tags"
  category = "categories"

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true

[Author]
  name = "CreepNT"

[params]
  description = "A stash of thoughts, projects and journeys followed by a baguette enthusiast."
  author = "CreepNT"
  copyright = "Copyright Â© 2020-20XX CreepNT"
  logo = ""

[frontmatter]
  date  = [":filename", ":default"]
  author = "CreepNT"
  github = "CreepNT"
  sitename = "CreepNT"
  twitter = "https://twitter.com/CreepNT4"
  summary="A stash of thoughts, projects and journeys followed by a baguette enthusiast."

[permalinks]
  posts = "/:year/:month/:day/:filename"
  pages = "/:slug"
  photos = "/:year/:month/:day/:filename"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML"]

[outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "atom"

[outputFormats.JSON]
  mediatype = "application/json"
  baseName = "feed"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[menu]
  [[menu.main]]
    identifier = "index"
    name       = "Index"
    url        = "/"
    weight     = -111

  [[menu.main]]
    identifier = "projects"
    name       = "Projects"
    url        = "/projects/"
    weight     = -30

  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about/"
    weight     = -20
